#!/bin/sh

if [ "$ACTION" = "remove" ]; then
    if [ `mount |grep "$1 "` ]; then
        echo "WARNING: SD card pulled out without unmounting first!"
        umount -f /dev/$1
    fi
    rmdir /media/$1

elif [ "$SUBSYSTEM" = "block" ]; then
	if ! [ `ls /sys/class/block/${1}?* 2>/dev/null` ]; then
		mkdir /media/$1
		mount /dev/$1 /media/$1 -o $2
		if [ $? -ne 0 ]; then rmdir /media/$1; fi
	fi

else
	if ! [ `ls /sys/class/ubi/${1}_?* 2>/dev/null` ]; then
		NAME=`cat /sys/class/ubi/${1}/name`
		mkdir /media/$NAME
		mount ubi:$NAME /media/$NAME -t ubifs -o $2
		if [ $? -ne 0 ]; then rmdir /media/$NAME; fi
	fi
fi
